### ISSUE TITLE
RTOS thread not work on LPC1768 board

### ISSUE THREAD

**Issue by 32duino** [platformio/platform-nxplpc#5]
RTOS thread not work on LPC1768 board. but same code work fine on stm32f103rb and FRDM K64F

Configuration

Win 7 64bit operate system:

PlatformIO Version:
Atom + PlatformIO IDE 2.0.0-beta.8 Core 3.5.0.a4

The content of platformio.ini:
```
[env:lpc1768]
platform = nxplpc
board = lpc1768
framework = mbed
build_flags = -Wall -lc -DPIO_FRAMEWORK_MBED_RTOS_PRESENT
```

Source file to reproduce issue:
```
#include "mbed.h"
#include "rtos.h"

DigitalOut led1(LED1);
DigitalOut led2(LED2);
Thread thread;

void led2_thread() {
while (true) {
led2 = !led2;
Thread::wait(1000);
}
}

int main() {
thread.start(led2_thread);

while (true) {
    led1 = !led1;
    Thread::wait(500);
}
}
```

**Comment by FusedShadowX** [comment]
I think this issue is a blocker. I used also the Freescale K64F and the same problem occurs. The error is thrown from an mbed internal library mbes_wait_api_rtos where the definition of thread::wait for some reason throws an undefined variable error. Even though I removed an reinstalled the framework the error didn't resolved the error. I opened an issue on ARM mbed_os repository because this error blocks the process of build.

**Comment by ivankravets** [comment]
Do you still have problems with RTOS?

**Comment by FusedShadowX** [comment]
Sorry for the delay, wasn't logged for long time. I saw that you included a fix. It is working properly know, the issue can be closed.

**Comment by ivankravets** [comment]
thanks for the report!
